name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v4
    - run: npm install
    - run: npm run build
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        rm: true
        source: "_site"
        target: "/srv/aurmartin/www"
        strip_components: 1
    - name: Cloudflare Cache Purge Action
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://api.cloudflare.com/client/v4/zones/bfd721ff421637d3d912b8d9ebedc22d/purge_cache
        method: "POST"
        customHeaders: |
          {
            "Content-Type": "application/json",
            "Authorization": "Bearer ${{ secrets.CLOUDFLARE_CACHE_KEY }}"
          }
        data: '{"purge_everything": true}'
